# get public age key from ssh key:
# sudo nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
# run to update encrypted file with new keys:
# nix-shell -p sops --run "sops updatekeys secrets/secrets.json"
keys:
  - &local age1qntsa6e2c9ete42ycs6rszhxytj7xujlvpz35n3fup6gdmhl0qcsf5sg6f
  - &node1 age1kxj0ws3zcjq6raw2k34qquj9yg4rjkjqa9ds2dprg2fx28nfkpeqr78zev
  - &node3 age1qu3wj03tnj2hyzgc3xza8n2lsm3df52veen7zrpksf48qjzqw9tstnuyfj
creation_rules:
  - path_regex: secrets/secrets.json$
    key_groups:
    - age:
      - *local
      - *node1
      - *node3
